#!/usr/bin/env python3

POLY = 0xEDB88320

def bit_matrix_crc32_byte():

    N = 40  

    state = [set() for _ in range(32)]
    for i in range(32):
        state[i] = {i}

    data_bits = [set([32 + j]) for j in range(8)]
    for i in range(8):
        state[i] = state[i] ^ data_bits[i]

    for _ in range(8):
        feedback = state[0]
        new_state = [set() for _ in range(32)]
        for i in range(31):
            new_state[i] = state[i + 1].copy()
        new_state[31] = set()
        poly_bits = []
        for i in range(32):
            if (POLY >> i) & 1:
                poly_bits.append(i)
        for i in poly_bits:
            new_state[i] = new_state[i] ^ feedback
        state = new_state

    return state


def build_multi_byte_matrix(n_bytes):
    total_inputs = 32 + 8 * n_bytes

    state = [set([i]) for i in range(32)]

    for byte_idx in range(n_bytes):
        for i in range(8):
            data_bit_idx = 32 + byte_idx * 8 + i
            state[i] = state[i] ^ {data_bit_idx}

        for _ in range(8):
            feedback = state[0]
            new_state = [set() for _ in range(32)]
            for i in range(31):
                new_state[i] = state[i + 1].copy()
            new_state[31] = set()
            for i in range(32):
                if (POLY >> i) & 1:
                    new_state[i] = new_state[i] ^ feedback
            state = new_state

    return state


def equations_to_sv(state, n_bytes):
    lines = []
    for i in range(32):
        taps = sorted(state[i])
        terms = []
        for t in taps:
            if t < 32:
                terms.append(f"c[{t}]")
            else:
                byte_idx = (t - 32) // 8
                bit_idx = (t - 32) % 8
                terms.append(f"d[{byte_idx * 8 + bit_idx}]")
        expr = " ^ ".join(terms) if terms else "1'b0"
        lines.append(f"        n[{i}] = {expr};")
    return "\n".join(lines)


def generate_sv():
    lines = []
    lines.append("// crc32_parallel.svh — Parallel CRC32 (Ethernet)")
    lines.append("// Auto-generated by scripts/gen_crc32.py")
    lines.append("// Pure combinational XOR trees, no loops or conditionals.")
    lines.append("// Include inside a module with `include \"crc32_parallel.svh\"")
    lines.append("//")
    lines.append("// Polynomial: 0xEDB88320 (reflected 0x04C11DB7)")
    lines.append("")
    lines.append("")

    for nb in range(1, 9):
        data_width = nb * 8
        state = build_multi_byte_matrix(nb)

        lines.append(f"    // CRC32 over {nb} byte(s) ({data_width} bits) — parallel")
        lines.append(f"    function automatic [31:0] crc32_{nb}byte;")
        lines.append(f"        input [31:0] c;       // current CRC state")
        lines.append(f"        input [{data_width-1}:0] d;  // data bytes (LSByte first)")
        lines.append(f"        reg [31:0] n;")
        lines.append(f"        begin")
        lines.append(equations_to_sv(state, nb))
        lines.append(f"            crc32_{nb}byte = n;")
        lines.append(f"        end")
        lines.append(f"    endfunction")
        lines.append("")

    lines.append("    // Dispatch by tkeep: compute CRC over valid bytes only")
    lines.append("    function automatic [31:0] crc32_64b;")
    lines.append("        input [31:0] crc_in;")
    lines.append("        input [63:0] tdata;")
    lines.append("        input [ 7:0] tkeep;")
    lines.append("        begin")
    lines.append("            case (tkeep)")
    lines.append("                8'hFF: crc32_64b = crc32_8byte(crc_in, tdata);")
    lines.append("                8'h7F: crc32_64b = crc32_7byte(crc_in, tdata[55:0]);")
    lines.append("                8'h3F: crc32_64b = crc32_6byte(crc_in, tdata[47:0]);")
    lines.append("                8'h1F: crc32_64b = crc32_5byte(crc_in, tdata[39:0]);")
    lines.append("                8'h0F: crc32_64b = crc32_4byte(crc_in, tdata[31:0]);")
    lines.append("                8'h07: crc32_64b = crc32_3byte(crc_in, tdata[23:0]);")
    lines.append("                8'h03: crc32_64b = crc32_2byte(crc_in, tdata[15:0]);")
    lines.append("                8'h01: crc32_64b = crc32_1byte(crc_in, tdata[ 7:0]);")
    lines.append("                default: crc32_64b = crc_in;")
    lines.append("            endcase")
    lines.append("        end")
    lines.append("    endfunction")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    import os
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "..", "rtl", "crc32_parallel.svh")
    sv_code = generate_sv()
    with open(out_path, "w") as f:
        f.write(sv_code + "\n")
    print(f"Generated {out_path}")

    import struct

    def crc32_ref(data_bytes):
        crc = 0xFFFFFFFF
        for b in data_bytes:
            crc ^= b
            for _ in range(8):
                if crc & 1:
                    crc = (crc >> 1) ^ POLY
                else:
                    crc >>= 1
        return crc

    test_data = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
    ref = crc32_ref(test_data)
    print(f"Reference CRC32 of {test_data}: 0x{ref:08X}")
    print(f"Final FCS would be: 0x{(~ref) & 0xFFFFFFFF:08X}")
